### ISSUE TITLE
[Bug]: Deployed app crash when selecting any variable from the filter panel

### ISSUE THREAD

**Issue by anajens** [insightsengineering/teal.gallery#125]
### What happened?

Click on link for deployed teal app (e.g. https://genentech.shinyapps.io/nest_basic-teal_stable/ ) --> 
Select filter panel variable (e.g. Iris Sepal.Length) -->  
app crashes

![image](https://github.com/insightsengineering/teal.gallery/assets/43623360/0aa67945-6115-48ce-9b8d-14de94c8e23f)

Locally the error in the console is:
```
Warning: Error in readLines: 'con' is not a connection
  1: runApp
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by pawelru** [comment]
@donyunardi this looks very similar to what you have reported on slack.

**Comment by donyunardi** [comment]
Thanks @pawelru, yes, we fixed this in `main` so just need to wait for release.

**Comment by vedhav** [comment]
Closing this because `teal.slice` release fixed this.
