### ISSUE TITLE
[Bug]: `{nest_basic-teal_dev}` `Error: object 'IRIS' not found`

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.gallery#135]
### What happened?

Go here https://genentech.shinyapps.io/nest_basic-teal_dev/ and click `Show R Code`. `IRIS` used in the code is written with capital letters, the same as `MTCARS` (instead of `iris` or `mtcars`). This brings an error when you run this code in your local session

<img width="761" alt="image" src="https://github.com/insightsengineering/teal.gallery/assets/133694481/e76ca116-9ecd-455d-ae91-44b4dcf5d3dc">

```r
warning('Code was not verified for reproducibility.')
# Add any code to install/load your NEST environment here

library(shiny)
library(teal.code)
library(teal.data)
library(teal.slice)
library(teal)

message('Preprocessing is empty')

stopifnot(rlang::hash(IRIS) == "34844aba7bde36f5a34f6d8e39803508")
stopifnot(rlang::hash(MTCARS) == "d0487363db4e6cc64fdb740cb6617fc0")

IRIS <- dplyr::filter(IRIS, Species == "setosa")
```

```r
Error: object 'IRIS' not found
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by pawelru** [comment]
This is actually not super wrong. You got the warning that the reproducibility is not enabled by the app author:
https://github.com/insightsengineering/teal.gallery/blob/0915c6b24fa46053c6a40aab4629781f1d6be51f/basic-teal/app.R#L6

The question is rather: should it be like that taking into account the _basicness_ of the app?

**Comment by vedhav** [comment]
Thanks for the PR, it's redeployed and works now.
<img width="1077" alt="Screenshot 2024-02-14 at 8 33 33 PM" src="https://github.com/insightsengineering/teal.gallery/assets/49812166/cadcc5c7-25c7-49ab-be05-0ce939b7e70f">

**Comment by vedhav** [comment]
> This is actually not super wrong. You got the warning that the reproducibility is not enabled by the app author:

@pawelru  we will merge the `dev` to `main` after `teal.transform` release.

**Comment by m7pr** [comment]
> should it be like that taking into account the basicness of the app?

I think teal.data usage is still basic usage
