### ISSUE TITLE
[Bug]: `{nest_exploratory_dev}` `Warning message: `aes_()` was deprecated in ggplot2 3.0.0. ℹ Please use tidy evaluation idioms with   `aes()``

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.gallery#138]
This is from running the Show R Code in Missing Data tab of https://genentech.shinyapps.io/nest_exploratory_dev/

**Comment by pawelru** [comment]
https://github.com/insightsengineering/teal.modules.general/issues/629

**Comment by m7pr** [comment]
Thanks @pawelru

**Comment by donyunardi** [comment]
so we can close this?

**Comment by m7pr** [comment]
yes, let's close this one as it is a duplicate
