### ISSUE TITLE
[Bug]: Teal apps from the gallery are not working

### ISSUE THREAD

**Issue by tatianakhandygo** [insightsengineering/teal.gallery#175]
### What happened?

Dear team,

It looks like a lot of reports from the apps in the teal gallery are not working. For example, [safety](https://genentech.shinyapps.io/nest_safety_stable/) - dm & ae tables. At the same time many reports are still working fine (most of the reports in [exploratory](https://genentech.shinyapps.io/nest_exploratory_stable/), for example).

![image](https://github.com/insightsengineering/teal.gallery/assets/121961626/fd020e3a-f8a1-4725-a3ab-c24754746505)

From the error text, it might be related to a [recent update](https://github.com/insightsengineering/rtables/blob/main/NEWS.md#rtables-0679007) in rtables happened on June 16th.
![image](https://github.com/insightsengineering/teal.gallery/assets/121961626/99f57496-bae8-4628-9a34-8a034c2779e3)

Thank you!

Kind regards,
Tatiana

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by pawelru** [comment]
Hi. Thanks for the report. We are experiencing incompatibility issues right now. It will be addressed once `rtables` will be approved by CRAN. 

Referencing: https://github.com/insightsengineering/tern/issues/1255#issuecomment-2180859983

**Comment by vedhav** [comment]
Thank you for reporting this @tatianakhandygo. This issue is resolved now.
<img width="1121" alt="Screenshot 2024-06-21 at 12 00 30 PM" src="https://github.com/insightsengineering/teal.gallery/assets/49812166/81eda59e-5d4b-43a7-86cf-b279e001b9f7">
