### ISSUE TITLE
[Question]: Python example

### ISSUE THREAD

**Issue by vindevoy** [insightsengineering/teal.gallery#180]
### What is your question?

Hi, in your python example, I don't see any Python code.  Should I be looking on a different branch for this ?  I already looked into the dev branch.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by pawelru** [comment]
Hi. It looks like the python code is stored as a string and then evaled using reticulate. It's [here](https://github.com/insightsengineering/teal.gallery/blob/42bc41a741b89013c42b2a1dedfd5cd25ec39284/python/app.R#L26-L42) and [here](https://github.com/insightsengineering/teal.gallery/blob/42bc41a741b89013c42b2a1dedfd5cd25ec39284/python/app.R#L50-L70).

Inside the running app, if you click show R code - it's available again as a very long string (we should probably style it better)
![image](https://github.com/user-attachments/assets/ee557530-1111-477e-917d-31a3c03b902c)

Does that answer your question?

**Comment by vindevoy** [comment]
Oh, yes.  Thank you.  It's just injected.

I thought I would find something written in Shiny for Python.
