### ISSUE TITLE
[Bug]: Exploratory App - Variable Browser - Filter Panel

### ISSUE THREAD

**Issue by Polkas** [insightsengineering/teal.gallery#19]
### What happened?

Regarding: https://genentech.shinyapps.io/nest_exploratory_main/

The filter panel selection update breaks the variable browser's selection.
I attached the video with the behavior.

https://user-images.githubusercontent.com/10676545/223667269-1ddb2ae7-8136-4f4e-ba25-4db87df6931f.mov

### Relevant log output

Not related

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by lcd2yyz** [comment]
Note this behavior does not replicate in the previous version of `teal` (v0.11.1) - possibly due to the changes when reporter feature was added.

**Comment by averissimo** [comment]
This might be fixed with this PR https://github.com/insightsengineering/teal.modules.general/pull/549

[Screencast from 2023-08-03 13-30-46.webm](https://github.com/insightsengineering/teal.gallery/assets/211358/fd8ff85d-eae7-4a1d-abc0-6832e31eab8b)
