### ISSUE TITLE
load scda specific data, instead of loading the whole snapshot then subset

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/teal.gallery#3]
If I recall correctly, there were some recent performance improvements in scda that allow to get single dataset instead of loading the whole collection of datasets. We might consider adding this here.
@shajoezhu am I right?

_Originally posted by @pawelru in https://github.com/insightsengineering/teal.gallery/pull/1#discussion_r1102569217_

**Comment by donyunardi** [comment]
I believe this is done.

For example:
https://github.com/insightsengineering/teal.gallery/blob/c3bcdf1ca8320e00f00231d5fd19877fa215bfe3/efficacy/app.R#L16C1-L16C44

Can we close this?

**Comment by pawelru** [comment]
Not really. It's about changing `synthetic_cdisc_data("latest")$xyz` into `synthetic_cdisc_dataset("latest", "adsl")`

Please have a look at the benchmark results. The difference is noticeable.
``` r
library(scda)
#> 
library(scda.2022)

# load the data once
invisible(synthetic_cdisc_data("latest")$adsl)
invisible(synthetic_cdisc_dataset("latest", "adsl"))

bench::mark(
    synthetic_cdisc_data("latest")$adsl,
    synthetic_cdisc_dataset("latest", "adsl"),
    check = FALSE
)
#> Warning: Some expressions had a GC in every iteration; so filtering is
#> disabled.
#> # A tibble: 2 × 6
#>   expression                           min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                      <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 "synthetic_cdisc_data(\"latest… 871.94ms 871.94ms      1.15     280MB     2.29
#> 2 "synthetic_cdisc_dataset(\"lat…   5.09ms   5.27ms    185.       813KB     1.99
```

<sup>Created on 2024-01-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by donyunardi** [comment]
Ah.. okay, thanks. Let's do this for this increment.

**Comment by m7pr** [comment]
wow the change is singnificat. can't believe it wasn't possible before to load just one dataset!

**Comment by m7pr** [comment]
Hey, the current approach could be simplified already by loading all data once in each script, but I took suggestions from this thread and went one step ahead where each time we just pull the specific CDISC dataset.

**Comment by shajoezhu** [comment]
can we remove the scda packages, and use random.cdisc.data package in the future, rcd also has cached data. we are going to stop maintaining the scda packages.

**Comment by m7pr** [comment]
@donyunardi can you create separate cards for that, and we can tackle this week.

**Comment by m7pr** [comment]
Created an issue for `{scda}` removal https://github.com/insightsengineering/teal.gallery/issues/154

**Comment by m7pr** [comment]
Closing this one as finished during https://github.com/insightsengineering/teal.gallery/pull/151
