### ISSUE TITLE
Remove formatters from renv.lock files

### ISSUE THREAD

**Issue by m7pr** [insightsengineering/teal.gallery#38]
A consequence of #34 and https://github.com/insightsengineering/teal.gallery/pull/35
`formatters` is no longer needed in renv.lock which means we can remove it, hence shorten the time of `renv::restore()`

**Comment by vedhav** [comment]
Closing this issue as we're moving away from `renv::restore()` in favor of installing dependencies from r-universe

**Comment by m7pr** [comment]
@vedhav but you can use renv::restore() and r-universe, but I guess we want to always work on newly recently deployed packages?

**Comment by vedhav** [comment]
Yeah, the idea was that we should make sure that the apps stay updated and always work on the latest release and main package versions.

**Comment by vedhav** [comment]
Yes, part of the reason for choosing this solution was that this also makes sure that the teal packages work well with the latest cran packages.

**Comment by m7pr** [comment]
alrighty, thanks for the explanation
