### ISSUE TITLE
`python` app doesn't start

### ISSUE THREAD

**Issue by chlebowa** [insightsengineering/teal.gallery#39]
When running 
```
source("https://raw.github.com/insightsengineering/teal.gallery/main/_internal/utils/sourceme.R")
restore_and_run("python")
```

I get 
```
Error in system2(python, args, stdout = TRUE, stderr = FALSE) :
error in running command
```

This is under R 4.2.2 on Ubuntu 20.04.

**Comment by vedhav** [comment]
Are you able to clone and run this app @chlebowa?

**Comment by vedhav** [comment]
Ah! I was able to reproduce it. Thanks for creating an issue for this.
Turnes out that if there is no Python virtual env called `example_env_name` in the path `/Users/username/.virtualenvs` it does not work.

**Comment by vedhav** [comment]
@chlebowa Can you check if this works for you?

```
source("https://raw.github.com/insightsengineering/teal.gallery/main/_internal/utils/sourceme.R")
restore_and_run("python", ref = "39-fix-python-restore@main")
```

**Comment by chlebowa** [comment]
Yes, now it works :+1:

**Comment by vedhav** [comment]
Can you please review PR  #40 that fixes this?
