### ISSUE TITLE
Remove `stringr` dependency

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.gallery#5]
I have found that there is only one usage of this package. Please think of an alternative and possibly remove it from the package dependency.

**Comment by donyunardi** [comment]
Line in question:
https://github.com/insightsengineering/teal.gallery/blob/00547871a0a0131857dc6938ea153edad3df2c5c/inst/apps/longitudinal/app.R#L177

### Acceptance Criteria
* Investigate if there's an alternative way to do this
* If found, remove stringr dependency and update code

**Comment by pawelru** [comment]
not applicable anymore
