### ISSUE TITLE
More meaningful ordering of demo apps

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/teal.gallery#53]
### Feature description

Teal demo app page may be one of the first places where a new user sees a teal app, thus having the demo apps arranged in a more logical order, for example, by increasing complexity, is more meaningful and easier to follow for first-time users.

Please consider rearrange the demo app (on both the links in Home page, and the gallery panels in Demo page) in the following order
1. basic-teal
2. exploratory
3. safety
4. efficacy
5. patient-profile
6. early-dev
7. longitudinal
8. RNA-seq
9. python

As we have quite a few presentations/workshops upcoming, please consider prioritizing this issue.

**Comment by vedhav** [comment]
Noting down to re-record the GIFs as there are some UI changes made linked to the teal.gallery improvement tasks.
