### ISSUE TITLE
More consistent title for demo teal apps

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/teal.gallery#55]
### Feature description

Linked to https://github.com/insightsengineering/teal.gallery/issues/13. For more consistent look/feel of demo teal apps, suggest to make the following changes

For all apps, show text "Teal @ Roche" to the top-right, and if possible add the teal hex.
@telepath37 or do you think it should show "NEST @ Roche" and the nest hex instead?

For text to show at top-left
1. basic-teal - My first teal app
2. exploratory - Example teal app for general dataset exploration with teal.modules.general 
3. safety - Example teal app focusing on safety analysis of clinical trial data with teal.modules.clinical
4. efficacy - Example teal app focusing on efficacy analysis of clinical trial data with teal.modules.clinical
5. patient-profile - Example teal app focusing on patient-level analysis of clinical trial data with teal.modules.clinical
6. early-dev - Example teal app focusing on analysis of early-phase clinical trial data with teal.osprey
7. longitudinal - Example teal app focusing on analysis of longitudinal clinical trial data with teal.goshawk
8. RNA-seq - Example teal app focusing on analysis of RNA-seq data with teal.modules.hermes
9. python - Example teal app using python dataset connector

As we have quite a few presentations/workshops upcoming, please consider prioritizing this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by chlebowa** [comment]
> For all apps, show text "Teal @ Roche" to the top-right, and if possible add the teal hex. @telepath37 or do you think it should show "NEST @ Roche" and the nest hex instead?

Actually, we could add the NEST icon to the browser tab header as well.
![browser_icon](https://github.com/insightsengineering/teal.gallery/assets/114988527/7709b162-e0fa-48f0-ae25-ea4d32d9b1c3)
