### ISSUE TITLE
[Bug]: Previewer image is moving even when cursor not hovering

### ISSUE THREAD

**Issue by lcd2yyz** [insightsengineering/teal.gallery#66]
### What happened?

Tiny but noticeable detail. If not too much effort, good to fix.
It's the most obvious in the `exploratory` or `early-dev` panel. Although my cursor is hovering over basic-teal or in the menu area, there is a scroll bar that keeps on moving. Shouldn't it be a static image if not cursor is not hovering over it?

https://github.com/insightsengineering/teal.gallery/assets/78242757/cacef0ef-7834-4981-9128-18dcdb82c380

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
As discussed, this is because the GIF size/element is larger than the static PNG size/element.
I will fix this in https://github.com/insightsengineering/teal.gallery/pull/72 as I need to redo the PNG and GIF due to logo update.
