### ISSUE TITLE
[Feature Request]: New app demoing all features of filter panel

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/teal.gallery#70]
### Feature description

New app with a few, identical and very simple module (to better see the difference) that will present module specific configuration as well as different types of the filters.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

### Contribution Guidelines

- [X] I agree to follow this project's Contribution Guidelines.

### Security Policy

- [X] I agree to follow this project's Security Policy.

**Comment by donyunardi** [comment]
### Acceptance Criteria
* Instead of making a new app, we'll fix the basic teal app in teal.gallery to include the different features of teal.slices
* Should cover all states of teal_slice (i.e. fixed, anchored)
* Should have module_specific
* Should have count_type
*
