### ISSUE TITLE
_dev or _stable?

### ISSUE THREAD

**Issue by donyunardi** [insightsengineering/teal.gallery#91]
https://github.com/insightsengineering/teal.gallery/blob/6cbee27c2e9c63e4b549a36170c109ad604bfc47/README.md?plain=1#L16-L26

Shouldn't the `Development version` points to `_dev` URL instead of `_stable`?

**Comment by hzhang2-cims** [comment]
Dear developers, 
I wanted to make sure that all these apps are currently dependent on development version right(as of 11/16/2023)? As I currently cannot load them following the readme instructions. (although I can open them online by clicking the link.)
```{r}
Sys.setenv(GITHUB_PAT = "I put my github token here")

source("https://raw.github.com/insightsengineering/teal.gallery/main/_internal/utils/sourceme.R")

# Run the basic-teal app
restore_and_run("basic-teal")
```
It keeps failing at the stage of setting up project libraries using renv. 
My local package version:
```
> packageVersion(pkg = "renv")
[1] ‘1.0.3’
> packageVersion(pkg = "teal")
[1] ‘0.14.0’
```
My R version: 4.3.1

----------------------------------------------------------------------------------------------------------------------------------

One more question: I found these modules that I can put together in [general analysis modules](https://insightsengineering.github.io/teal.modules.general/), which is an awesome point to begin exploring. But when I tried looking for the independent modules in [teal.modules.clinical](https://insightsengineering.github.io/teal.modules.clinical/latest-tag/). I found that there are no available code of already built modules there that I can try playing with, only the following two articles. Could you kindly guide me to the document(if there is one) where there are some example code of well-built modules using `teal.modules.clinical `(stable version) that I can try out?
![image](https://github.com/insightsengineering/teal.gallery/assets/138268177/0dd03c0b-a423-46f4-84b5-860104ca5d0b)


Thanks in advance for reviewing my questions.

**Comment by m7pr** [comment]
@donyunardi 

> Shouldn't the Development version points to _dev URL instead of _stable?

If we want to have different URLs in the README for different branches then this is doable - each branch has a different content of this file. However if we ever plan to merge one to another then the file would get overwritten.

So we either 

- have a different content on dev branch, and we keep remembering not to overwrite README during each PR. On `master<-dev` PR we actually do branch copy of `dev@main` from `dev` and we position a PR as `main <- dev@main`. We could revert links on `dev@main` so they are the same as on `main`. 

- or we point to a website from README and the website redirects between `dev` and `stable` apps

- or we have links to both `stable` and `dev` versions of the apps in a README in all branches (my preferred option)

What do you think @vedhav ?

**Comment by vedhav** [comment]
Yeah, `Development version` should be renamed as `Stable version`. I think it's worth displaying both stable and dev versions of the app in a table like this instead, created a PR for the same:

| Dev version   | Stable version |
|---------------|----------------|
| basic-teal    | basic-teal     |
| exploratory   | exploratory    |
| safety        | safety         |
| efficacy      | efficacy       |
| patient-profile | patient-profile |
| early-dev     | early-dev      |
| longitudinal  | longitudinal   |
| RNA-seq        | RNA-seq         |
| python        | python         |

**Comment by vedhav** [comment]
@hzhang2-cims Can you try the local spp run steps once again?
All the modules present in `teal.modules.general` and `teal.modules.clinical` have a working example in their function documentation. So, I would recommend having a look at them from the [reference page](https://insightsengineering.github.io/teal.modules.clinical/latest-tag/reference/index.html).
Additionally, you can also have a look at the [TLG-Catalog](https://insightsengineering.github.io/tlg-catalog/stable/tables/adverse-events/aet01.html) which explains more about the data processing steps followed by the teal app creation.
